apis/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings

from rest_framework_nested import routers
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


from .views import (
    FarmViewSet,
    FarmParcelViewSet,
    GenericFarmAssetSerializerViewSet,
    FarmCropViewSet,
    FarmAnimalViewSet,
    AgriculturalMachineViewSet,
    FarmCalendarActivityViewSet,
    FarmCalendarActivityTypeViewSet,
    FertilizationOperationViewSet,
    FertilizerViewSet,
    IrrigationOperationViewSet,
    CropProtectionOperationViewSet,
    PesticideViewSet,
    ObservationViewSet,
    CropStressIndicatorObservationViewSet,
    CropGrowthStageObservationViewSet,
    CompostOperationViewSet,
    AddRawMaterialOperationViewSet,
    CompostTurningOperationViewSet,
)

router = routers.DefaultRouter()

router.register(r'Farm', FarmViewSet)
router.register(r'FarmParcels', FarmParcelViewSet)
router.register(r'GenericFarmAssets', GenericFarmAssetSerializerViewSet)
router.register(r'FarmCrops', FarmCropViewSet)
router.register(r'FarmAnimals', FarmAnimalViewSet)
router.register(r'AgriculturalMachines', AgriculturalMachineViewSet)
router.register(r'FarmCalendarActivities', FarmCalendarActivityViewSet)
router.register(r'FarmCalendarActivityTypes', FarmCalendarActivityTypeViewSet)
router.register(r'FertilizationOperations', FertilizationOperationViewSet)
router.register(r'Fertilizers', FertilizerViewSet)
router.register(r'IrrigationOperations', IrrigationOperationViewSet)
router.register(r'CropProtectionOperations', CropProtectionOperationViewSet)
router.register(r'Pesticides', PesticideViewSet)
router.register(r'Observations', ObservationViewSet)
router.register(r'CropStressIndicatorObservations', CropStressIndicatorObservationViewSet)
router.register(r'CropGrowthStageObservations', CropGrowthStageObservationViewSet)
router.register(r'AddRawMaterialOperations', AddRawMaterialOperationViewSet)
router.register(r'CompostOperations', CompostOperationViewSet)
router.register(r'CompostTurningOperations', CompostTurningOperationViewSet)


compost_operations_router = routers.NestedSimpleRouter(router, r'CompostOperations', lookup='compost_operation')
compost_operations_router.register(r'AddRawMaterialOperations', AddRawMaterialOperationViewSet, basename=f'compost-operation-addrawmaterialoperation')
compost_operations_router.register(r'IrrigationOperations', IrrigationOperationViewSet, basename=f'compost-operation-irrigationoperation')
compost_operations_router.register(r'Observations', ObservationViewSet, basename=f'compost-operation-observation')
compost_operations_router.register(r'CompostTurningOperations', CompostTurningOperationViewSet, basename=f'compost-turning-operation-observation')




urlpatterns = [
    path('api/', lambda request: redirect('api-root', settings.SHORT_API_VERSION)),
    path('api/<str:version>/', include([
        path('', include(router.urls)),  # Register versioned API routes
        path('', include(compost_operations_router.urls)),  # Register versioned API routes
        path('schema/', SpectacularAPIView.as_view(), name='schema'),  # Schema generation
        path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),  # Swagger UI
        path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),  # ReDoc
    ])),
]

farm_activities/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required


from .views import (
    CalendarView,
    FarmCalendarActivityTypeListView,
    FarmCalendarActivityTypeCreateView,
    FarmCalendarActivityTypeEditView,
    FarmCalendarActivityCreateByTypeView,
    FarmCalendarActivityListView,
    FarmCalendarActivityEdit,
    PreRegisterCalendarActivityView,
    FarmCalendarActivityAutocomplete,
)



urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('register-activity/select-type', PreRegisterCalendarActivityView.as_view(), name='pre_register_calendar_activity'),
    path('register-activity/<str:activity_type>', FarmCalendarActivityCreateByTypeView.as_view(), name='create_calendar_activity'),
    path('activities/', FarmCalendarActivityListView.as_view(), name='calendar_activity_list'),
    path('activities/<uuid:pk>/', FarmCalendarActivityEdit.as_view(), name='calendar_activity_edit'),
    path('activity-type/create/', FarmCalendarActivityTypeCreateView.as_view(), name='create_activity_type'),
    path('activity-types/', FarmCalendarActivityTypeListView.as_view(), name='list_activity_type'),
    path('activity-types/<uuid:pk>/', FarmCalendarActivityTypeEditView.as_view(), name='edit_activity_type'),
    path('activities-autocomplete/', FarmCalendarActivityAutocomplete.as_view(), name='activities-autocomplete'),
]

farm_calendar/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("farm_management.urls")),
    path("", include("farm_activities.urls")),
    path("", include("apis.urls")),
]

# # should be on an apis app
# from harvesthand.views import FarmAreaViewSet, FarmPlantViewSet, FarmAnimalViewSet, FarmEquipmentViewSet
# from farmactivities.views import FarmActivityViewSet, FarmActivityTypeViewSet

# router = routers.DefaultRouter()
# router.register(r'FarmAreas', FarmAreaViewSet)
# router.register(r'FarmPlants', FarmPlantViewSet)
# router.register(r'FarmAnimals', FarmAnimalViewSet)
# router.register(r'FarmEquipments', FarmEquipmentViewSet)
# router.register(r'FarmActivities', FarmActivityViewSet)
# router.register(r'FarmActivityTypes', FarmActivityTypeViewSet)

# urlpatterns += [
#     path('api/', include(router.urls)),
# ]

urlpatterns += staticfiles_urlpatterns()

farm_activities/models.py
import uuid
import datetime
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator

from django.conf import settings


class FarmCalendarActivityType(models.Model):
    """
    This refers to a generic types of activity that is displayed on the farm calendar.
    It is used to represent both observation types and operation types,
    with a descrition of what is this type of activity, and the colors that should be used
    to represent this in the calendar.
    The list of default farm activity types is set on settings.DEFAULT_CALENDAR_ACTIVITY_TYPES.
    These default types are main activity types (observations and operations) already identified
    during development. However, the user may add their own generic activity type that is not
    covered by the defaults.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, editable=False, unique=True,
                          blank=False, null=False, verbose_name='ID')
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    # Fields for color codes
    background_color = models.CharField(
        max_length=7,
        validators=[RegexValidator(regex='^#[0-9A-Fa-f]{6}$', message='Enter a valid hex color code.')],
        default='#007bff',  # Default color
    )
    border_color = models.CharField(
        max_length=7,
        validators=[RegexValidator(regex='^#[0-9A-Fa-f]{6}$', message='Enter a valid hex color code.')],
        default='#007bff',  # Default color
    )
    text_color = models.CharField(
        max_length=7,
        validators=[RegexValidator(regex='^#[0-9A-Fa-f]{6}$', message='Enter a valid hex color code.')],
        default='#000000',  # Default text color
    )

    class ActivityCategoryChoices(models.TextChoices):
        ACTIVITY = 'activity', _('Activity')
        OBSERVATION = 'observation', _('Observation')
        ALERT = 'alert', _('Alert')

    category = models.CharField(max_length=50, choices=ActivityCategoryChoices.choices,
                                        default=ActivityCategoryChoices.ACTIVITY)


    def __str__(self):
        return self.name


class FarmCalendarActivity(models.Model):
    """
    An occurrence of some farm activity on the calendar.
    This will be the base for both the operations and observations, as in
    how they are presented in a calendar and what type of activity (or event) this is about.
    """
    class Meta:
        verbose_name = "Farm Activity"
        verbose_name_plural = "Farm Activities"

    ACTIVITY_NAME = None

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, editable=False, unique=True,
                          blank=False, null=False, verbose_name='ID')

    activity_type = models.ForeignKey(FarmCalendarActivityType, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    start_datetime = models.DateTimeField(default=datetime.datetime.now)
    end_datetime = models.DateTimeField(blank=True, null=True)

    details = models.TextField(blank=True, null=True)

    responsible_agent = models.CharField(blank=True, null=True)
    # need to change this into a operation model instead...
    agricultural_machinery = models.ManyToManyField('farm_management.AgriculturalMachine', related_name='used_in_operations', blank=True)
    # weather_observation = models.ManyToManyField('farm_management.AgriculturalMachine', related_name='used_in_operations', blank=True, null=True)?



    parent_activity = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="nested_activities",  # This will act as the reverse relation
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.title} ({self.start_datetime.strftime('%Y-%m-%d %H:%M')})"

    def save(self, *args, **kwargs):
        if self.activity_type is None and self.ACTIVITY_NAME is not None:
            self.activity_type, _ = FarmCalendarActivityType.objects.get_or_create(name=self.ACTIVITY_NAME)

        if self.title is None or self.title == '':
            self.title = self.activity_type.name

        super().save(*args, **kwargs)


class FertilizationOperation(FarmCalendarActivity):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['fertilization']['name']
    class Meta:
        verbose_name = "Fertilization Operation"
        verbose_name_plural = "Fertilization Operations"

    # treated_area = models.IntegerField(blank=True, null=True)
    # fertilization_type = models.CharField(max_length=255, blank=True, null=True)
    applied_amount = models.DecimalField(max_digits=10, decimal_places=2)
    applied_amount_unit = models.CharField(max_length=255)

    application_method = models.CharField(max_length=255, blank=True, null=True)

    operated_on = models.ForeignKey('farm_management.FarmParcel', on_delete=models.CASCADE)
    fertilizer = models.ForeignKey('farm_management.Fertilizer', on_delete=models.SET_NULL, blank=True, null=True)



class IrrigationOperation(FarmCalendarActivity):

    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['irrigation']['name']

    class Meta:
        verbose_name = "Irrigation Operation"
        verbose_name_plural = "Irrigation Operations"

    class IrrigationSystemChoices(models.TextChoices):
        SPRINKLER = 'sprinkler', _('Sprinkler')
        DRIP = 'drip', _('Drip')
        CENTRE_PIVOT  = 'centre_pivot', _('Centre Pivot')
        FURROW  = 'furrow', _('Furrow')
        TERRACED  = 'terraced', _('Terraced')

    applied_amount = models.DecimalField(max_digits=10, decimal_places=2)
    applied_amount_unit = models.CharField(max_length=255)

    operated_on = models.ForeignKey('farm_management.FarmParcel', on_delete=models.CASCADE, blank=True, null=True)

    irrigation_system = models.CharField(max_length=50, choices=IrrigationSystemChoices.choices,
                                        default=IrrigationSystemChoices.SPRINKLER)

    # def save(self, *args, **kwargs):
    #     self.activity_type, _ = FarmCalendarActivityType.objects.get_or_create(name=settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['irrigation']['name'])
    #     super().save(*args, **kwargs)



class CropProtectionOperation(FarmCalendarActivity):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['crop_protection']['name']

    class Meta:
        verbose_name = "Crop Protection Operation"
        verbose_name_plural = "Crop Protection Operations"


    applied_amount = models.DecimalField(max_digits=10, decimal_places=2)
    applied_amount_unit = models.CharField(max_length=255)

    operated_on = models.ForeignKey('farm_management.FarmParcel', on_delete=models.CASCADE)
    pesticide = models.ForeignKey('farm_management.Pesticide', on_delete=models.SET_NULL, blank=True, null=True)



class Observation(FarmCalendarActivity):
    sensor_id = models.CharField(_('Made By Sensor'), max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = "Observation"
        verbose_name_plural = "Observations"

    value = models.CharField(max_length=255)
    value_unit = models.CharField(max_length=255, blank=True, null=True)
    observed_property = models.CharField(max_length=255)


class CropStressIndicatorObservation(Observation):

    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['crop_stress_indicator']['name']

    class Meta:
        verbose_name = "Crop Stress Indicator Observation"
        verbose_name_plural = "Crop Stress Indicator Observations"

    crop = models.ForeignKey('farm_management.FarmCrop', on_delete=models.CASCADE, blank=False, null=False)


class CropGrowthStageObservation(Observation):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['crop_growth_stage']['name']

    class Meta:
        verbose_name = "Crop Growth Stage Observation"
        verbose_name_plural = "Crop Growth Stage Observations"

    crop = models.ForeignKey('farm_management.FarmCrop', on_delete=models.CASCADE, blank=False, null=False)

    def save(self, *args, **kwargs):
        self.crop.growth_stage = self.value
        self.crop.save()
        super().save(*args, **kwargs)


class CompostOperation(FarmCalendarActivity):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['compost_operation']['name']

    class Meta:
        verbose_name = "Compost Operation"
        verbose_name_plural = "Compost Operations"

    compost_pile_id = models.CharField('Operated On Compost Pile', max_length=355)



class CompostTurningOperation(FarmCalendarActivity):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['compost_turning_operation']['name']

    class Meta:
        verbose_name = "Compost Turning Operation"
        verbose_name_plural = "Compost Turning Operations"


class AddRawMaterialOperation(FarmCalendarActivity):
    ACTIVITY_NAME = settings.DEFAULT_CALENDAR_ACTIVITY_TYPES['add_raw_material_operation']['name']

    class Meta:
        verbose_name = "Add Raw Material Operation"
        verbose_name_plural = "Add Raw Material Operations"


    compost_materials = models.ManyToManyField('farm_management.CompostMaterial', through='farm_activities.AddRawMaterialCompostQuantity')


class AddRawMaterialCompostQuantity(models.Model):
    class Meta:
        verbose_name = "Raw Material Quantity for Operation"
        verbose_name_plural = "Raw Material Quantities for Operation"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, db_index=True, editable=False, unique=True,
                          blank=False, null=False, verbose_name='ID')

    operation = models.ForeignKey(AddRawMaterialOperation, on_delete=models.CASCADE)

farmactivities/views/rest_api.py
from rest_framework import permissions, viewsets

from farmactivities.models import FarmActivity, FarmActivityType
from farmactivities.serializers import FarmActivitySerializer, FarmActivityTypeSerializer


class FarmActivityViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows FarmActivity to be viewed or edited.
    """
    queryset = FarmActivity.objects.all().order_by('-start_time')
    serializer_class = FarmActivitySerializer
    permission_classes = [permissions.IsAuthenticated]


class FarmActivityTypeViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows FarmActivityType to be viewed or edited.
    """
    queryset = FarmActivityType.objects.all().order_by('-name')
    serializer_class = FarmActivityTypeSerializer
    permission_classes = [permissions.IsAuthenticated]

templates/farm_activities/activities/activity_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}

    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">

{% endblock extra_css %}


{% block page_content_title %}{% if is_edit %}Edit {{ form.instance.activity_type }}{% else %}Register New {{ form.activity_type.initial }}{% endif %}{% endblock %}

{% block page_content_rows %}
        <!-- Page Content Rows with Card -->
        <div class="row">
            <div class="col-xl-8 col-lg-8">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">{% if is_edit %}Edit {{ form.instance.activity_type }}{% else %}Register New {{ form.activity_type.initial }}{% endif %}</h6>
                    </div>

                    <!-- Card Body -->
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-success">Save</button>
                            {% if is_edit %}
                                <button type="button" class="btn btn-danger" id="deleteButton" data-url="{{ delete_url }}">Delete</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>

{% endblock %}




{% block on_dom_load_js %}
{% if is_edit %}
    $('#deleteButton').on('click', function () {
        // Get the delete URL from the button's data-url attribute
        var deleteUrl = $(this).data('url');

        // Show a confirmation dialog
        if (confirm("Are you sure you want to delete this item?")) {
            $.ajax({
                url: deleteUrl,  // URL to send the DELETE request
                type: 'DELETE',
                success: function (response) {
                    alertify.success('{{ form.instance.activity_type }} was deleted.');
                    window.location.href = '{% url 'calendar' %}';
                },
                error: function (xhr) {
                    alertify.error('Error deleting {{ form.instance.activity_type }}.');
                }
            });
        }
    });

{% endif %}

// Select2 for the parent_activity field

{% if form.parent_activity %}
    $('#id_parent_activity').select2({
        placeholder: 'Select a Activity',
        allowClear: true,
        ajax: {
            url: "{% url 'activities-autocomplete' %}",  // Use the reverse URL lookup for your autocomplete view
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    term: params.term,  // Pass the term entered by the user
                };
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        return {
                            text: item.activity,  // Display the activity string (the result from str())
                            id: item.pk,  // The pk is required for the selection
                        };
                    }),
                };
            },
            cache: true,
        },
        minimumInputLength: 1,  // Trigger the search after the first character
    });

    // Load initial selection for parent_activity field (if there is an initial value)
    var initialParentActivityValue = "{{ form.instance.parent_activity.id }}";  // Use the current value of parent_activity
    if (initialParentActivityValue) {
        $.ajax({
            url: "{% url 'activities-autocomplete' %}",
            data: { term: initialParentActivityValue },
            dataType: 'json',
        }).done(function (data) {
            if (data.length > 0) {
                var newOption = new Option(data[0].activity, data[0].pk, true, true);
                $('#id_parent_activity').append(newOption).trigger('change');
            }
        });
    }
{% endif %}

{% endblock on_dom_load_js %}

{% block body_end_extra_scripts %}
    <!-- alertifyjs js -->
    <script src="{% static 'libs/alertifyjs/build/alertify.min.js' %}"></script>
    <script src="{% static 'vendor/select2/js/select2.min.js' %}"></script>
{% endblock body_end_extra_scripts %}

templates/farm_activities/activities/activity_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'vendor/pickr/themes/classic.min.css' %}">

<style>
    .pickr-container {
        display: inline-block;
        margin-left: 10px;
    }
</style>
{% endblock %}


{% block page_content_title %}{% if is_edit %}Edit{% else %}Add New{% endif %} Farm Calendar Activity Type{% endblock %}

{% block page_content_rows %}

        <!-- Page Content Rows with Card -->
        <div class="row">
            <div class="col-xl-8 col-lg-8">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">{% if is_edit %}Edit{% else %}Add New{% endif %} Farm Calendar Activity Type</h6>
                    </div>

                    <!-- Card Body -->
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>

{% endblock %}




{% block body_end_extra_scripts %}
<script src="{% static 'vendor/pickr/pickr.min.js' %}"></script>
{% endblock body_end_extra_scripts %}


{% block on_dom_load_js %}


const pickrs_input = document.querySelectorAll('.color-picker');

pickrs_input.forEach(input => {
    const pickrContainer = document.createElement('div');
    pickrContainer.classList.add('pickr-container');
    // Insert the new <div> after the input field

    input.style.display = 'none';
    input.parentNode.insertBefore(pickrContainer, input.nextSibling);

    const pickr = Pickr.create({
        el: pickrContainer,  // Use the new <div> as the Pickr container
        theme: 'classic',
        default: input.value || '#ffffff',  // Set default color if available
        components: {
            preview: true,
            opacity: true,
            hue: true,
            interaction: {
                hex: true,
                rgba: true,
                input: true,
                save: true
            }
        }
    });
    pickr.on('save', (color) => {
        const defaultColor = '#ffffff'; // Replace with your desired default color
        const colorValue = color ? color.toHEXA().toString() : defaultColor;
        input.setAttribute("value", colorValue);
    });
});
{% endblock on_dom_load_js %}

templates/farm_activities/activities/activity_types.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Calendar Activity Types{% endblock title %}

{% block extra_css %}
    <!-- Page-specific stylesheets -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet">

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- alertifyjs Css -->
    <link href="{% static 'libs/alertifyjs/build/css/alertify.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- alertifyjs default themes  Css -->
    <link href="{% static 'libs/alertifyjs/build/css/themes/default.min.css' %}" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">

{% endblock extra_css %}

{% block page_content_title %}Farm Calendar Activity Types{% endblock %}

{% block page_content_rows %}

<!-- DataTable - Only displayed in add mode -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Manage Calendar Activity Types</h4>
            </div>

            <!-- Card Body -->
            <div class="card-body">
             <a href="{% url 'create_activity_type' %}" class="btn btn-primary mb-3">Register New Calendar Activity Type</a>
            </div>

            <div class="card-body">
                {% include 'snippets/data_tables/_data_tables.html' with ignore_dt_status=True data=data_json data_form=data_form datatable_fields=datatable_fields row_id_field='pk' asset_base_url=asset_base_url asset_base_api_url=asset_base_api_url table_id='assetsDatatable' extra_deletion_confirmation_message="The deletion of this activity type cannot be undone, and it will remove any instances of this activity from the calendar. Do you wish to proceed?" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block body_end_extra_scripts %}
    <!-- Required datatable js -->
    <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Responsive datatables -->
    <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

    <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>

    <!-- Column visibility -->
    <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

    <!-- alertifyjs js -->
    <script src="{% static 'libs/alertifyjs/build/alertify.min.js' %}"></script>

{% endblock body_end_extra_scripts %}


{% block on_dom_load_js %}

{% endblock on_dom_load_js %}

templates/farm_activities/activities/pre_activity_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_content_title %}Select the Activity Type{% endblock %}

{% block page_content_rows %}

        <!-- Page Content Rows with Card -->
        <div class="row">
            <div class="col-xl-8 col-lg-8">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Select the Activity Type</h6>
                    </div>

                    <!-- Card Body -->
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-success">Next</button>
                        </form>
                    </div>
                </div>
            </div>
{% endblock %}