apis/urls.py
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings

from rest_framework_nested import routers
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


from .views import (
    FarmViewSet,
    FarmParcelViewSet,
    GenericFarmAssetSerializerViewSet,
    FarmCropViewSet,
    FarmAnimalViewSet,
    AgriculturalMachineViewSet,
    FarmCalendarActivityViewSet,
    FarmCalendarActivityTypeViewSet,
    FertilizationOperationViewSet,
    FertilizerViewSet,
    IrrigationOperationViewSet,
    CropProtectionOperationViewSet,
    PesticideViewSet,
    ObservationViewSet,
    CropStressIndicatorObservationViewSet,
    CropGrowthStageObservationViewSet,
    CompostOperationViewSet,
    AddRawMaterialOperationViewSet,
    CompostTurningOperationViewSet,
)

router = routers.DefaultRouter()

router.register(r'Farm', FarmViewSet)
router.register(r'FarmParcels', FarmParcelViewSet)
router.register(r'GenericFarmAssets', GenericFarmAssetSerializerViewSet)
router.register(r'FarmCrops', FarmCropViewSet)
router.register(r'FarmAnimals', FarmAnimalViewSet)
router.register(r'AgriculturalMachines', AgriculturalMachineViewSet)
router.register(r'FarmCalendarActivities', FarmCalendarActivityViewSet)
router.register(r'FarmCalendarActivityTypes', FarmCalendarActivityTypeViewSet)
router.register(r'FertilizationOperations', FertilizationOperationViewSet)
router.register(r'Fertilizers', FertilizerViewSet)
router.register(r'IrrigationOperations', IrrigationOperationViewSet)
router.register(r'CropProtectionOperations', CropProtectionOperationViewSet)
router.register(r'Pesticides', PesticideViewSet)
router.register(r'Observations', ObservationViewSet)
router.register(r'CropStressIndicatorObservations', CropStressIndicatorObservationViewSet)
router.register(r'CropGrowthStageObservations', CropGrowthStageObservationViewSet)
router.register(r'AddRawMaterialOperations', AddRawMaterialOperationViewSet)
router.register(r'CompostOperations', CompostOperationViewSet)
router.register(r'CompostTurningOperations', CompostTurningOperationViewSet)


compost_operations_router = routers.NestedSimpleRouter(router, r'CompostOperations', lookup='compost_operation')
compost_operations_router.register(r'AddRawMaterialOperations', AddRawMaterialOperationViewSet, basename=f'compost-operation-addrawmaterialoperation')
compost_operations_router.register(r'IrrigationOperations', IrrigationOperationViewSet, basename=f'compost-operation-irrigationoperation')
compost_operations_router.register(r'Observations', ObservationViewSet, basename=f'compost-operation-observation')
compost_operations_router.register(r'CompostTurningOperations', CompostTurningOperationViewSet, basename=f'compost-turning-operation-observation')




urlpatterns = [
    path('api/', lambda request: redirect('api-root', settings.SHORT_API_VERSION)),
    path('api/<str:version>/', include([
        path('', include(router.urls)),  # Register versioned API routes
        path('', include(compost_operations_router.urls)),  # Register versioned API routes
        path('schema/', SpectacularAPIView.as_view(), name='schema'),  # Schema generation
        path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),  # Swagger UI
        path('schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),  # ReDoc
    ])),
]

farm_calendar/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("farm_management.urls")),
    path("", include("farm_activities.urls")),
    path("", include("apis.urls")),
]

# # should be on an apis app
# from harvesthand.views import FarmAreaViewSet, FarmPlantViewSet, FarmAnimalViewSet, FarmEquipmentViewSet
# from farmactivities.views import FarmActivityViewSet, FarmActivityTypeViewSet

# router = routers.DefaultRouter()
# router.register(r'FarmAreas', FarmAreaViewSet)
# router.register(r'FarmPlants', FarmPlantViewSet)
# router.register(r'FarmAnimals', FarmAnimalViewSet)
# router.register(r'FarmEquipments', FarmEquipmentViewSet)
# router.register(r'FarmActivities', FarmActivityViewSet)
# router.register(r'FarmActivityTypes', FarmActivityTypeViewSet)

# urlpatterns += [
#     path('api/', include(router.urls)),
# ]

urlpatterns += staticfiles_urlpatterns()

farm_management/urls.py
from django.urls import path
from .views import (
    login_view,
    logout_view,
    post_authentication,
    FarmParcelView,
    FarmView,
    AjaxHandlerView,
    GenericFarmAssetListView,
    GenericFarmAssetUpdateView,
    FarmCropListView,
    FarmCropUpdateView,
    FarmAnimalListView,
    FarmAnimalUpdateView,
    AgriculturalMachineListView,
    AgriculturalMachineUpdateView,
    FertilizerListView,
    FertilizerUpdateView,
    PesticideListView,
    PesticideUpdateView,
    AnimalGroupAutocomplete,
    PrepareReportView,
)


urlpatterns = [
    path("login/", login_view, name="login"),
    path("post_auth/", post_authentication, name="post_auth"),
    path("logout/", logout_view, name="logout"),
    # Ajax routes for toggling status and deletion
    # this has to be changed to use the actual API, otherwise we are creating two
    # different APIs in the system, and instead we shoud use one if we want to retrieve JSON(or JSON-LD)
    # representation of the models
    path(
        "<str:prefix>/ajax/<str:action>/<uuid:pk>/",
        view=AjaxHandlerView.as_view(),
        name="action",
    ),
    path('farm-animals/animal-group-autocomplete/', AnimalGroupAutocomplete.as_view(), name='animal-group-autocomplete'),
    path("farms/", FarmView.as_view(), name="farms"),
    path("farms/<uuid:pk>/", view=FarmView.as_view(), name="farm_edit"),
    path("farm-parcels/", FarmParcelView.as_view(), name="farm_parcels"),
    path("farm-parcels/<uuid:pk>/", view=FarmParcelView.as_view(), name="farm_parcel_edit",),

    path("generic-assets/", GenericFarmAssetListView.as_view(), name="generic_farm_assets"),
    path("generic-assets/<uuid:pk>/", GenericFarmAssetUpdateView.as_view(), name="generic_farm_asset_edit"),
    path("farm-crops/", FarmCropListView.as_view(), name="farm_crops"),
    path("farm-crops/<uuid:pk>/", FarmCropUpdateView.as_view(), name="farm_crop_edit"),
    path("farm-animals/", FarmAnimalListView.as_view(), name="farm_animals"),
    path("farm-animals/<uuid:pk>/", FarmAnimalUpdateView.as_view(), name="farm_animal_edit"),
    path("agri-machines/", AgriculturalMachineListView.as_view(), name="agri_machines"),
    path("agri-machines/<uuid:pk>/", AgriculturalMachineUpdateView.as_view(), name="agri_machine_edit"),

    path("fertilizers/", FertilizerListView.as_view(), name="fertilizers"),
    path("fertilizers/<uuid:pk>/", FertilizerUpdateView.as_view(), name="fertilizer_edit"),

    path("pesticides/", PesticideListView.as_view(), name="pesticides"),
    path("pesticides/<uuid:pk>/", PesticideUpdateView.as_view(), name="pesticide_edit"),
    path("reports/<str:report_type>/", PrepareReportView.as_view(), name="prepare_report"),
]

farm_management/models/farm_assets.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .base import NamedHistoricalBaseModel, BaseModel


class FarmAsset(NamedHistoricalBaseModel):
    class Meta:
        # keep as abstract for now, maybe if we need to query
        # all assets in general, then it would make sense to have a
        # table for this model
        abstract = True

    description = models.TextField(blank=True, null=True)
    parcel = models.ForeignKey('FarmParcel', on_delete=models.SET_NULL,blank=True, null=True,
                               related_name="%(class)ss")


class GenericFarmAsset(NamedHistoricalBaseModel):
    class Meta:
        verbose_name = "Generic Farm Asset"
        verbose_name_plural = "Generic Farm Assets"

    description = models.TextField(blank=True, null=True)
    parcel = models.ForeignKey('FarmParcel', on_delete=models.SET_NULL,blank=True, null=True,
                               related_name="%(class)ss")

    def __str__(self):
        return f"{self.name}"


class FarmCrop(FarmAsset):
    class Meta:
        verbose_name = "Farm Crop"
        verbose_name_plural = "Farm Crops"

    species = models.CharField(max_length=255)
    variety = models.CharField(max_length=255, blank=True, null=True)

    growth_stage = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.name} - {self.species} - {self.variety} - {self.growth_stage}"


class FarmAnimal(FarmAsset):
    class Meta:
        verbose_name = "Farm Animal"
        verbose_name_plural = "Farm Animals"

    class SexChoices(models.IntegerChoices):
        NONE = 0, _('N/A')
        FEMALE = 1, _('Female')
        MALE = 2, _('Male')

    name = models.CharField(_('Name'), max_length=100, blank=True, null=True)
    national_id = models.CharField(_('National ID'), blank=True, null=True)
    species = models.CharField(max_length=255)
    breed = models.CharField(max_length=255, blank=True, null=True)
    birth_date = models.DateTimeField()
    sex = models.IntegerField(choices=SexChoices.choices, default=SexChoices.NONE)
    castrated = models.BooleanField(default=False)
    animal_group = models.CharField(max_length=255, blank=True, null=True)
    entry_date = models.DateField(null=True, blank=True)
    leaving_date = models.DateField(null=True, blank=True)
    previous_owner = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        s = f"{self.species} - {self.breed}"
        if self.animal_group:
            s += f' ({self.animal_group})'
        return s


class AgriculturalMachine(FarmAsset):
    class Meta:
        verbose_name = "Farm Machine"
        verbose_name_plural = "Farm Machines"

    purchase_date = models.DateField()
    manufacturer = models.CharField(max_length=255)
    model = models.CharField(max_length=255)
    seria_number = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name} - {self.manufacturer} - {self.model}'


class FarmSensor(FarmAsset):
    class Meta:
        verbose_name = "Farm Sensor"
        verbose_name_plural = "Farm Sensors"

    # not sure this should be here... gonna leave out for now
    # data_stream_uri = models.URLField()
    sensor_type = models.CharField()
    public = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.sensor_type}'

farm_management/forms/farm_assets.py
from django import forms
from django.conf import settings
from django.forms import modelform_factory

from dal import autocomplete


def get_generic_farm_asset_form(model):
    GenericFarmAssetForm = modelform_factory(
        model,
        fields="__all__",
        exclude=['id', 'deleted_at'],
        widgets={
            'birth_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'purchase_date': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'animal_group': autocomplete.ListSelect2(url='animal-group-autocomplete'),

            'entry_date': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'leaving_date': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
            'previous_owner': forms.TextInput(attrs={'placeholder': 'Previous owner name'}),
        },
    )
    return GenericFarmAssetForm

apis/views/farm_assets.py
from rest_framework import permissions, viewsets

from farm_management.models import (
    GenericFarmAsset,
    FarmCrop,
    FarmAnimal,
    AgriculturalMachine,
)
from ..serializers import (
    GenericFarmAssetSerializer,
    FarmCropSerializer,
    FarmAnimalSerializer,
    AgriculturalMachineSerializer,
)



class GenericFarmAssetSerializerViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows GenericFarmAsset to be viewed or edited.
    """
    queryset = GenericFarmAsset.objects.all().order_by('-created_at')
    serializer_class = GenericFarmAssetSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_fields = ['name', 'parcel', 'status']


class FarmCropViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows FarmCrop to be viewed or edited.
    """
    queryset = FarmCrop.objects.all().order_by('-created_at')
    serializer_class = FarmCropSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_fields = ['name', 'parcel', 'species', 'variety', 'growth_stage', 'status']


class FarmAnimalViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows FarmAnimal to be viewed or edited.
    """
    queryset = FarmAnimal.objects.all().order_by('-created_at')
    serializer_class = FarmAnimalSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_fields = ['name', 'parcel', 'animal_group', 'status']


class AgriculturalMachineViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows AgriculturalMachine to be viewed or edited.
    """
    queryset = AgriculturalMachine.objects.all().order_by('-created_at')
    serializer_class = AgriculturalMachineSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_fields = ['name', 'parcel', 'status']

farm_management/views/AjaxHandlerView.py
from django.db import models, transaction, DatabaseError
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator

from ..models.farm_parcels import FarmMaster, FarmParcel


MODEL_MAP = {
    "farms": FarmMaster,
    "farm-parcel": FarmParcel
}


@method_decorator(never_cache, name='dispatch')
class AjaxHandlerView(View):
    def post(self, request, prefix=None, action=None, pk=None):
        # Handle missing prefix by providing a default response or error
        if prefix and prefix in MODEL_MAP:
            model = MODEL_MAP[prefix]
        elif not prefix:
            # Handle cases with no prefix - general actions
            model = None  # No specific model required for general actions
        else:
            return JsonResponse({"error": "Invalid type"}, status=400)

        # Map action names to methods
        action_methods = {
            "toggle-status": self.toggle_status,
            "delete": self.delete_object
        }

        # Check if action is in the method mapping
        if action in action_methods:
            return action_methods[action](request, model, pk)
        elif not action:
            return JsonResponse({"error": "No action specified"}, status=400)
        else:
            return JsonResponse({"error": "Invalid action"}, status=400)

    def toggle_status(self, request, model, pk):
        if not model or not pk:
            return JsonResponse({"error": "Missing subject or primary key for toggling status."}, status=400)

        # Get the object and toggle its status
        obj = get_object_or_404(model, pk=pk)
        if obj.status == obj.BaseModelStatus.ACTIVE:
            obj.status = obj.BaseModelStatus.INACTIVE
            message = f"{model._meta.verbose_name} has been deactivated."
        else:
            obj.status = obj.BaseModelStatus.ACTIVE
            message = f"{model._meta.verbose_name} has been activated."

        obj.save()  # Save the updated status

        # Return the updated status and message
        return JsonResponse({"farm_status": obj.status, "message": message})

    @transaction.atomic
    def delete_object(self, request, model, pk):
        if not model or not pk:
            return JsonResponse({"error": "Missing subject or primary key for deletion."}, status=400)

        # Get the object and perform a soft delete
        obj = get_object_or_404(model, pk=pk)

        try:
            # Only call soft_delete on the main object
            if hasattr(obj, 'soft_delete') and hasattr(obj, 'status'):
                obj.soft_delete()  # This triggers cascading soft deletes if conditions are met

            message = f"{model._meta.verbose_name} and related records have been deleted."
            return JsonResponse({"message": message})
        except DatabaseError as e:
            return JsonResponse({"error": f"Failed to delete {model._meta.verbose_name}. Error: {str(e)}"},
                                status=400)

farm_management/views/reports.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from farm_calendar.utils.jwt_utils import get_token_from_jwt_request



class PrepareReportView(TemplateView, LoginRequiredMixin):
    template_name = "farm_management/reports/prepare_report.html"

    REPORT_TYPE = {
        'livestock': _('Livestock'),
        'irrigation': _('Irrigation'),
        'composting': _('Composting'),
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        readable_report_type = self.REPORT_TYPE[kwargs.get('report_type')]
        report_endpoint = settings.REPORTING_ENDPOINTS.get(kwargs.get('report_type'))
        report_result_base_endpoint = settings.REPORTING_ENDPOINTS.get('report_result_base')
        context['readable_report_type'] = readable_report_type
        context['report_endpoint'] = report_endpoint
        context['report_result_base_endpoint'] = report_result_base_endpoint
        token = get_token_from_jwt_request(self.request)
        context['access_token'] = token
        return context

templates/farm_management/farm_assets/farm_assets.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ model_name }}{% endblock title %}

{% block extra_css %}
    <!-- Page-specific stylesheets -->
    <link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet">

    <!-- Responsive datatable examples -->
    <link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- alertifyjs Css -->
    <link href="{% static 'libs/alertifyjs/build/css/alertify.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- alertifyjs default themes  Css -->
    <link href="{% static 'libs/alertifyjs/build/css/themes/default.min.css' %}" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">

{% endblock extra_css %}

{% block page_content_title %}{{ model_name }}{% endblock %}

{% block page_content_rows %}
<div class="row">
    <div class="col-sm-12">
        <div class="card shadow mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h4 class="card-title mb-0">{% if is_edit %}Edit{% else %}Add{% endif %} {{ model_name }}</h4>
                <!-- Toggle button to show/hide the form -->
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#dataFormCollapse"
                        aria-expanded="true" aria-controls="dataFormCollapse">
                    <i class="fas fa-chevron-down"></i> <!-- Icon for collapsing -->
                </button>
            </div>

            <div id="dataFormCollapse" class="card-body collapse{% if is_edit or form.errors %} show{% endif %}">
                <form method="post">
                    {% csrf_token %}
                    {{ form | crispy }}

                    {% if is_edit %}
                        <!-- Show Update button for edit mode -->
                        <button class="btn btn-primary w-md" type="submit" id="submit_btn">Update</button>
                        <button type="button" class="btn btn-danger w-md" onclick="location.href='{{asset_base_url}}'">Cancel</button>
                    {% else %}
                        <!-- Show Submit button for add mode -->
                        <button class="btn btn-success w-md" type="submit" id="submit_btn">Submit</button>
                        <button class="btn btn-secondary w-md" type="reset" id="reset">Reset</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>


{% if is_edit %}
{% else %}
<!-- DataTable - Only displayed in add mode -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ model_name }} Available</h4>
            </div>
            <div class="card-body">
                {% include 'snippets/data_tables/_data_tables.html' with data=data_json data_form=form datatable_fields=datatable_fields row_id_field='pk' asset_base_url=asset_base_url asset_base_api_url=asset_base_api_url table_id='assetsDatatable' %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block body_end_extra_scripts %}
    <!-- Required datatable js -->
    <script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Responsive datatables -->
    <script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

    <script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>

    <!-- Column visibility -->
    <script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

    <!-- alertifyjs js -->
    <script src="{% static 'libs/alertifyjs/build/alertify.min.js' %}"></script>

    <script src="{% static 'vendor/select2/js/select2.min.js' %}"></script>
{% endblock body_end_extra_scripts %}


{% block on_dom_load_js %}

    var initialAnimalGroupValue = "{{ form.instance.animal_group }}";
    $('#id_animal_group').select2({
        placeholder: 'Select an animal group',
        allowClear: true,
        tags: true,  // Enables user input for new values
        createTag: function (params) {
            var term = $.trim(params.term);
            if (term === '') {
                return null;
            }
            return {
                id: term,
                text: term,
                newTag: true  // Mark as new for styling if needed
            };
        },
        ajax: {
            url: "{% url 'animal-group-autocomplete' %}",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    term: params.term,
                };
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        return {
                            text: item,
                            id: item,
                        };
                    }),
                };
            },
            cache: true,
        },
        minimumInputLength: 1,
    });

    // Load initial selection
    if (initialAnimalGroupValue) {
        $.ajax({
            url: "{% url 'animal-group-autocomplete' %}",
            data: { term: initialAnimalGroupValue },
            dataType: 'json',
        }).done(function (data) {
            if (data.length > 0) {
                var newOption = new Option(data[0], data[0], true, true);
                $('#id_animal_group').append(newOption).trigger('change');
            }
        });
    }
{% endblock on_dom_load_js %}